### ISSUE TITLE
justBookmarks

### ISSUE THREAD

**Issue by OemNet** [magicmarcy/justBookmarks#61] opened 2023-01-08 08:26 UTC
When building on a personal server

I don't understand the procedure.

What kind of procedure do you build on a personal server?

1. Where is the file that describes the DB?
2. Are there any DB files to build?
3. Is there anything else I should do?

I would appreciate it if you could tell me.

**Comment by magicmarcy** [comment] 2023-01-08 10:24
Hello OemNet,

thank you for messaaging me. You're right, the data is stored in a Sqlite database. I've not implemented any kind of setup and tbh, I didn't expected anyone would ever use it on his own server^^.

The main reason for this is, that I think that this project hasn't been finishes yet and there is so much more stuff to do that the GitHub-Issues show. I made this as my private and as a "cool to do"-project first.

If you are familar with PHP you can easily watch the functions.php and create the needed tables in the database. I think that's all you have to do. It's just a spimple PHP Project.

But i will take care of your response and will add a kind of setup in the future.

Feel free to answer if there a furter questions.

**Comment by OemNet** [comment] 2023-01-08 10:46
Hello magic marcy

I am not good at programming.

I couldn't reproduce it completely by looking at the program.

I'm really sorry for being selfish.

Is it possible to receive the simplified version of Sqlite data?

If it is difficult to publish, you can also use the following address.

cloud6.meteos%gmail.com

Please convert from % to @.

**Comment by magicmarcy** [comment] 2023-01-08 10:50
Hello OemNet,

I will add a demo database with all the needed tables and data to this repository during the day.

**Comment by OemNet** [comment] 2023-01-08 10:59
hello magic mercy

thank you very much.

Waiting for your update.

**Comment by magicmarcy** [comment] 2023-01-08 11:14
Hey OemNet,

I created a simple Sqlite-File with just the needed parameters and attached it here. 

You can simply make a directory in your project folder justbookmarks/db and put the bookmarkservice.db into it.
Now you can open the project in you browser and register yourself an account.

[bookmarkservice.zip](https://github.com/magicmarcy/justBookmarks/files/10368219/bookmarkservice.zip)

**Comment by OemNet** [comment] 2023-01-08 11:36
Hey magic mercy.

I was able to add the DB successfully, but the site is not displayed.

Looking at the error log, it seems that it stopped at functions.php.

What is causing this?

![image6370_202318](https://user-images.githubusercontent.com/13575877/211194019-2429daf6-298c-4c0b-b93b-adca9e819a57.png)
![image6372_202318](https://user-images.githubusercontent.com/13575877/211194021-e8080c40-6e6e-43d2-b239-4f57cc36f163.png)
![image6374_202318](https://user-images.githubusercontent.com/13575877/211194022-f09bc94f-158d-4c70-8ca7-80b40f330eed.png)

**Comment by OemNet** [comment] 2023-01-08 11:38
Hey magic mercy.

I was able to add the DB successfully, but the site is not displayed.

Looking at the error log, it seems that it stopped at functions.php.

What is causing this?

![image6370_202318](https://user-images.githubusercontent.com/13575877/211194077-73f22a45-366e-4133-ae91-dd421125bfcb.png)
![image6372_202318](https://user-images.githubusercontent.com/13575877/211194082-498e7d6d-54d9-4e53-a80c-24e437a864e1.png)
![image6374_202318](https://user-images.githubusercontent.com/13575877/211194083-d5904d23-3e7c-454c-876f-37c57d158286.png)

**Comment by magicmarcy** [comment] 2023-01-08 11:52
Hey OemNet,

seems, there is no UserId. The function who causes the issue is called from the main.php - directly after your login.

Did you registered your account successfully?
Did the issue happend after your login?

I took the sample database locally and it seems to work fine.

Maybe you can attach the logfile from the log-folder here for further analytics.

**Comment by OemNet** [comment] 2023-01-08 12:32
Hey magical mercy.

I set up bookmarkservice.db as follows and installed it in the root directory /db.

the error remains the same.

The screen also shows a 500 error.

Are the settings correct?

![image6381_202318](https://user-images.githubusercontent.com/13575877/211196147-d9245357-e1e8-4e47-b59b-dd0a7ab3edbc.png)
![image6387_202318](https://user-images.githubusercontent.com/13575877/211196149-01cd9618-17ad-4436-8148-8de2d6d49cc2.png)
![image6388_202318](https://user-images.githubusercontent.com/13575877/211196151-a026d9af-b03f-4801-858b-e4579776d5d3.png)
![image6389_202318](https://user-images.githubusercontent.com/13575877/211196155-41fd4177-1aa3-43ad-849c-ac997ba5ef17.png)

**Comment by magicmarcy** [comment] 2023-01-08 12:41
Hello OemNet,

it seem, you added the User-Entry by hand and not by the registration-process. That's not how it works - you can not edit userdata manually.

Delete the user-entry, start your server and navigate to the address where you've deployed the app.

On the main-page click on "Registrieren" under the login button. There will be an new form where you can register a new account.

After you've finished that and there was shown a success-message on the top of the page you can go back to the loginpage to login with your account.

**Comment by OemNet** [comment] 2023-01-08 13:17
Hey magical mercy.

Even the site screen was not displayed because the PHP version was old.

When I tried it on another server, the screen was displayed.

Since there is no Registrieren link, I typed in the URL, but an error occurred.

![image6390_202318](https://user-images.githubusercontent.com/13575877/211198045-8078ac9e-2133-43dd-96a2-ac3c373236ee.png)
![FireShot Capture 017 - justBookmarks - Deine Bookmarks, überall verfügbar, in jedem Browser!_ - test denpa cloud](https://user-images.githubusercontent.com/13575877/211198048-327f9872-b546-4197-a75e-25400e5fed9d.png)
![image6391_202318](https://user-images.githubusercontent.com/13575877/211198050-3825fbff-4cec-40ff-8d5f-df4b5ed9baf9.png)

**Comment by OemNet** [comment] 2023-01-08 13:18
Hey magical mercy.

Even the site screen was not displayed because the PHP version was old.

When I tried it on another server, the screen was displayed.

Since there is no Registrieren link, I typed in the URL, but an error occurred.

![image6390_202318](https://user-images.githubusercontent.com/13575877/211198125-886506aa-6ea9-46e6-9eb6-8a17d3a83623.png)
![FireShot Capture 017 - justBookmarks - Deine Bookmarks, überall verfügbar, in jedem Browser!_ - test denpa cloud](https://user-images.githubusercontent.com/13575877/211198127-009b9ef0-97ec-4692-9cb3-14922437e570.png)
![image6391_202318](https://user-images.githubusercontent.com/13575877/211198128-eed009dd-70e8-45ea-80bd-e0f01ec78942.png)

**Comment by magicmarcy** [comment] 2023-01-08 13:42
Hello OemNet,

there is a parameter (REGISTRATION_ALLOWED) which allows a registration or not. In the database I attached here, the parameter value was 1 which means it is allowed. The register.php checks this value by itself so you can't access this page manually if the param is set to 0.

But it seems, that there is no database conection.

I think there is a problem with the PHP-configuration and PDO - a technical error so no connection can be established. 

I think I can't help you out at this point.

**Comment by OemNet** [comment] 2023-01-08 14:06
Hey magical mercy.

Thank you for everything.

I have a few other machines and will try them.

Thank you very much for your kindness.

**Comment by OemNet** [comment] 2023-01-08 15:28
Hey magical mercy.

Often there are no excuses.

Could you tell me about the following items?
1. PHP version
2. SQLite
3. Packages required to run the site

I would appreciate it if you could tell me.

**Comment by magicmarcy** [comment] 2023-01-08 15:38
Hello OemNet,

in this case I'm using
PHP-Version 8.0.13, 
PDO enabled, 
pdo_sqlite 3.27.2

Nothing required what is not included in PHP i think.

Will this help you?

**Comment by OemNet** [comment] 2023-01-10 10:26
Hey magical mercy.

Late reply. very sorry.

Information was helpful!

I tried to summarize what was built from the initial state in the article. (Sorry in Japanese.)
http://memorandum.cloud/2023/01/03/1744/

I downloaded the source code with git, but there was no DB file, so I wrote the URL of this forum in the article.

I will modify the article when it is incorporated into the source code in git.

**Comment by magicmarcy** [comment] 2023-02-01 21:32
I will close this topic. No new updates or information for three weeks. If you have problems, please open a new issue.

**Closed by magicmarcy** 2023-02-01 21:32 UTC
Labels: documentation
